//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public string disname { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> chotso { get; set; }
        public string sticknote { get; set; }
        public int luong { get; set; }
        public int phucap { get; set; }
        public string bankno { get; set; }
        public string bank_name { get; set; }
        public int isNV { get; set; }
        public int hasNote { get; set; }
        public string phoneno { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public string hktt { get; set; }
        public string sogiayto { get; set; }
        public Nullable<System.DateTime> ngaycap_gt { get; set; }
        public string noicap_gt { get; set; }
        public int is_uq { get; set; }
        public string email { get; set; }
        public Nullable<int> manager { get; set; }
        public int sta { get; set; }
    }
}
