//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> MorningCheckInActual { get; set; }
        public Nullable<System.DateTime> MorningCheckOutActual { get; set; }
        public Nullable<System.DateTime> AfternoonCheckInActual { get; set; }
        public Nullable<System.DateTime> AfternoonCheckOutActual { get; set; }
        public Nullable<System.DateTime> MorningCheckInManual { get; set; }
        public Nullable<System.DateTime> MorningCheckOutManual { get; set; }
        public Nullable<System.DateTime> AfternoonCheckInManual { get; set; }
        public Nullable<System.DateTime> AfternoonCheckOutManual { get; set; }
        public string LateReason { get; set; }
        public double TotalHours { get; set; }
    }
}
