//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int id { get; set; }
        public string name { get; set; }
        public int parent_id { get; set; }
        public int type { get; set; }
        public int wf { get; set; }
        public int kind { get; set; }
        public int pair { get; set; }
        public Nullable<int> nhom { get; set; }
        public int duyet { get; set; }
        public int theodoi { get; set; }
        public int tamung { get; set; }
        public int status { get; set; }
    }
}
