//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int Id { get; set; }
        public System.Guid ChatSessionId { get; set; }
        public string Role { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ChatSession ChatSession { get; set; }
    }
}
