//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chotso
    {
        public int id { get; set; }
        public System.DateTime ngaythang { get; set; }
        public int account_id { get; set; }
        public string ghichu { get; set; }
        public long tienthu { get; set; }
        public long tienchi { get; set; }
        public long tiencon { get; set; }
        public long tienchenhlech { get; set; }
        public long nogiang { get; set; }
        public long noduy { get; set; }
        public long notin { get; set; }
        public long nokhac { get; set; }
        public int sta { get; set; }
    }
}
