//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.HoSoes = new HashSet<HoSo>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public int address_id { get; set; }
        public int service_id { get; set; }
        public long amount { get; set; }
        public long consuming { get; set; }
        public System.DateTime time { get; set; }
        public int time_exp { get; set; }
        public int deadline { get; set; }
        public int status { get; set; }
        public string note { get; set; }
        public int account_id { get; set; }
        public int Priority { get; set; }
        public int partner { get; set; }
        public string sodienthoai { get; set; }
        public string sodienthoai_mota { get; set; }
        public int type { get; set; }
        public int rose { get; set; }
        public int outrose { get; set; }
        public int dove { get; set; }
        public int remunerate { get; set; }
        public int soanthao { get; set; }
        public string HardFileLink { get; set; }
        public int loai { get; set; }
        public int nguoiky_id { get; set; }
        public int nguoitheodoi_id { get; set; }
        public string googlemap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSo> HoSoes { get; set; }
    }
}
