//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuocHop
    {
        public int id { get; set; }
        public string name { get; set; }
        public int type { get; set; }
        public string vande { get; set; }
        public string ketqua { get; set; }
        public string ghichu { get; set; }
        public int taoboi { get; set; }
        public Nullable<System.DateTime> time_duyet { get; set; }
        public System.DateTime time { get; set; }
        public int hoso_id { get; set; }
        public string noidung { get; set; }
        public string bienban { get; set; }
        public string tailieuthamkhao { get; set; }
        public int mucdo { get; set; }
        public int status { get; set; }
    }
}
