//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class di1cua
    {
        public int id { get; set; }
        public int contract_id { get; set; }
        public int hoso_id { get; set; }
        public System.DateTime ngaynop { get; set; }
        public System.DateTime ngaytra { get; set; }
        public int canbo1cua { get; set; }
        public string canbophutrach { get; set; }
        public Nullable<int> noinhan_id { get; set; }
        public string maphieuhen { get; set; }
        public string ghichu { get; set; }
        public int trangthai { get; set; }
        public int type { get; set; }
    }
}
