//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class didiachinh
    {
        public int id { get; set; }
        public int contract_id { get; set; }
        public System.DateTime ngaynop { get; set; }
        public int noinop { get; set; }
        public int is_xa { get; set; }
        public int trangthai { get; set; }
    }
}
