//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dove
    {
        public int id { get; set; }
        public int hoso_id { get; set; }
        public int status { get; set; }
        public System.DateTime time { get; set; }
        public string scan_bia { get; set; }
        public Nullable<System.DateTime> time_start { get; set; }
        public Nullable<System.DateTime> time_tradiem { get; set; }
        public Nullable<System.DateTime> time_vexong { get; set; }
        public Nullable<System.DateTime> time_dongdau { get; set; }
        public Nullable<System.DateTime> time_thamdinh { get; set; }
        public string note { get; set; }
        public int account_id { get; set; }
    }
}
