//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dovelichsu
    {
        public int id { get; set; }
        public int hoso_id { get; set; }
        public int account_id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<System.DateTime> time_exp { get; set; }
        public int dove_account { get; set; }
    }
}
