//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSHoSo
    {
        public int id { get; set; }
        public long amount { get; set; }
        public long consuming { get; set; }
        public System.DateTime time { get; set; }
        public int status { get; set; }
        public int address_id { get; set; }
        public int customer_id { get; set; }
        public string address_name { get; set; }
        public string customer_name { get; set; }
        public int service_id { get; set; }
        public string service_name { get; set; }
        public int partner { get; set; }
        public string partner_name { get; set; }
        public int rose { get; set; }
        public int outrose { get; set; }
        public int dove { get; set; }
        public string HardFileLink { get; set; }
        public int loai { get; set; }
        public int account_id { get; set; }
        public string fullname { get; set; }
        public int step { get; set; }
        public string step_name { get; set; }
    }
}
