//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSMotCua
    {
        public string name { get; set; }
        public string canbo_name { get; set; }
        public string customer_name { get; set; }
        public int id { get; set; }
        public int contract_id { get; set; }
        public System.DateTime ngaynop { get; set; }
        public System.DateTime ngaytra { get; set; }
        public int canbo1cua { get; set; }
        public string canbophutrach { get; set; }
        public string maphieuhen { get; set; }
        public string ghichu { get; set; }
        public int trangthai { get; set; }
        public string c_xa { get; set; }
        public string e_giayuyquyenso { get; set; }
        public string e_hoten { get; set; }
        public string service_name { get; set; }
        public int contract_status { get; set; }
        public int step { get; set; }
        public int type { get; set; }
        public int service_id { get; set; }
        public int account_id { get; set; }
        public int address_id { get; set; }
        public int partner { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<System.DateTime> exp { get; set; }
    }
}
