//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public long id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> type { get; set; }
        public int contract_id { get; set; }
        public Nullable<int> hoso_id { get; set; }
    }
}
