//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fk_congviec_hoso
    {
        public long id { get; set; }
        public int congviec_id { get; set; }
        public int hoso_id { get; set; }
        public int status { get; set; }
    }
}
