//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoNhanGiayTo
    {
        public int id { get; set; }
        public int contract_id { get; set; }
        public int account_id { get; set; }
        public string giayto { get; set; }
        public string noinhan { get; set; }
        public string nguoinhan { get; set; }
        public System.DateTime ngaygiao { get; set; }
        public Nullable<System.DateTime> ngayhan { get; set; }
        public int trangthai { get; set; }
    }
}
