//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoPerson
    {
        public int Id { get; set; }
        public int HoSoId { get; set; }
        public int PersonInfoId { get; set; }
        public int Role { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsCertificateHolder { get; set; }
    
        public virtual HoSo HoSo { get; set; }
        public virtual PersonInfo PersonInfo { get; set; }
    }
}
