//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoSo()
        {
            this.HoSoPersons = new HashSet<HoSoPerson>();
        }
    
        public int id { get; set; }
        public int contract_id { get; set; }
        public string name { get; set; }
        public System.DateTime time_created { get; set; }
        public Nullable<System.DateTime> time_complete { get; set; }
        public int account_id { get; set; }
        public int account_id_soanthao { get; set; }
        public int service_id { get; set; }
        public string link_filecad { get; set; }
        public string link_gmap { get; set; }
        public string link_filecad_qr { get; set; }
        public string link_gmap_qr { get; set; }
        public string link_flycam { get; set; }
        public int step_id { get; set; }
        public string note { get; set; }
        public int priority { get; set; }
        public int trang4 { get; set; }
        public int status { get; set; }
        public Nullable<int> ngoaigiao { get; set; }
        public Nullable<int> light { get; set; }
        public Nullable<int> LandParcelId { get; set; }
        public Nullable<int> VariationInfoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoPerson> HoSoPersons { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Service Service { get; set; }
        public virtual LandParcel LandParcel { get; set; }
        public virtual VariationInfo VariationInfo { get; set; }
    }
}
