//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InOut
    {
        public long id { get; set; }
        public string code { get; set; }
        public int category_id { get; set; }
        public int account_id { get; set; }
        public int type { get; set; }
        public string note { get; set; }
        public System.DateTime time { get; set; }
        public int created_by { get; set; }
        public Nullable<int> contract_id { get; set; }
        public int gostock { get; set; }
        public int status { get; set; }
        public Nullable<int> state { get; set; }
        public int currency { get; set; }
        public long amount { get; set; }
        public Nullable<int> inoutchoduyet_id { get; set; }
        public int unlock { get; set; }
        public Nullable<int> xclass { get; set; }
    }
}
