//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public long id { get; set; }
        public string name { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime exp_date { get; set; }
        public int created_by { get; set; }
        public int process_by { get; set; }
        public string note { get; set; }
        public int status { get; set; }
        public Nullable<int> hoso_id { get; set; }
        public Nullable<int> progress_type { get; set; }
        public Nullable<int> label { get; set; }
    }
}
