//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandParcel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LandParcel()
        {
            this.HoSoes = new HashSet<HoSo>();
        }
    
        public int Id { get; set; }
        public string CertificateNumber { get; set; }
        public string ParcelNumber { get; set; }
        public string MapSheet { get; set; }
        public Nullable<decimal> ActualArea { get; set; }
        public Nullable<decimal> CertifiedArea { get; set; }
        public string UsagePurpose { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Issuer { get; set; }
        public string BookNumber { get; set; }
        public Nullable<int> address_id { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSo> HoSoes { get; set; }
    }
}
