//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string title { get; set; }
        public string contents { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int account_id { get; set; }
    }
}
