//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int id { get; set; }
        public string code { get; set; }
        public string disname { get; set; }
        public string name { get; set; }
        public string sodienthoai { get; set; }
        public int sothutu { get; set; }
        public int account_id { get; set; }
        public string id_no { get; set; }
        public string id_type { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public string bankno { get; set; }
        public string bankname { get; set; }
        public string bankbrand { get; set; }
        public Nullable<System.DateTime> pro_date { get; set; }
        public string pro_by { get; set; }
        public Nullable<int> cbdp_id { get; set; }
    }
}
