//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerAccount
    {
        public Nullable<int> account_id { get; set; }
        public string fullname { get; set; }
        public string name { get; set; }
        public string sodienthoai { get; set; }
        public string id_no { get; set; }
        public string id_type { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> sothutu { get; set; }
    }
}
