//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonInfo()
        {
            this.HoSoPersons = new HashSet<HoSoPerson>();
            this.PersonInfo1 = new HashSet<PersonInfo>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; } //a_hoten
        public Nullable<System.DateTime> BirthDate { get; set; } //a_ngaysinh
        public string Gender { get; set; } // a_gioitinh
        public string DocumentType { get; set; } // a_loaigiayto
        public string DocumentNumber { get; set; } // a_sogiayto
        public Nullable<System.DateTime> IssueDate { get; set; } // a_ngaycap_gt
        public string Issuer { get; set; } // a_noicap_gt
        public string TaxCode { get; set; } // a_masothue
        public Nullable<System.DateTime> DeathDate { get; set; } // a_ngaymat
        public string DeathDocument { get; set; } 
        public Nullable<int> HeirId { get; set; } 
        public Nullable<int> address_id { get; set; } // a_hktt 

        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoPerson> HoSoPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonInfo> PersonInfo1 { get; set; }
        public virtual PersonInfo PersonInfo2 { get; set; }
    }
}
