//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceByArea
    {
        public int id { get; set; }
        public int type { get; set; }
        public int area { get; set; }
        public string text { get; set; }
        public int price { get; set; }
        public string note { get; set; }
    }
}
