//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporter
    {
        public long id { get; set; }
        public int account_id { get; set; }
        public System.DateTime time { get; set; }
        public string thoigian { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string result { get; set; }
        public string note { get; set; }
    }
}
