//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<long> amount { get; set; }
        public Nullable<int> stt { get; set; }
        public string trainning { get; set; }
        public int thoihan { get; set; }
        public int nhacnho { get; set; }
        public int phananh { get; set; }
        public int tocao { get; set; }
        public Nullable<int> reward { get; set; }
    }
}
