//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocker
    {
        public long id { get; set; }
        public long amount { get; set; }
        public string note { get; set; }
        public int currency { get; set; }
        public int type { get; set; }
        public System.DateTime time { get; set; }
        public int sta { get; set; }
        public int state { get; set; }
    }
}
