//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TachHop
    {
        public long id { get; set; }
        public int infomation_id { get; set; }
        public int type { get; set; }
        public string a_loaigiayto { get; set; }
        public string a_sogiayto { get; set; }
        public string a_hoten { get; set; }
        public Nullable<System.DateTime> a_ngaysinh { get; set; }
        public string a_gioitinh { get; set; }
        public string a_quoctich { get; set; }
        public string a_nguyenquan { get; set; }
        public string a_hktt { get; set; }
        public string a_thon { get; set; }
        public string a_xa { get; set; }
        public string a_huyen { get; set; }
        public string a_tinh { get; set; }
        public Nullable<System.DateTime> a_ngaycap_gt { get; set; }
        public string a_noicap_gt { get; set; }
        public string a_masothue { get; set; }
        public string a_loaigiayto1 { get; set; }
        public string a_sogiayto1 { get; set; }
        public string a_hoten1 { get; set; }
        public Nullable<System.DateTime> a_ngaysinh1 { get; set; }
        public string a_gioitinh1 { get; set; }
        public string a_quoctich1 { get; set; }
        public string a_nguyenquan1 { get; set; }
        public string a_hktt1 { get; set; }
        public Nullable<System.DateTime> a_ngaycap_gt1 { get; set; }
        public string a_noicap_gt1 { get; set; }
        public Nullable<int> b_csh { get; set; }
        public string b_hoten { get; set; }
        public Nullable<System.DateTime> b_ngaysinh { get; set; }
        public string b_loaigiayto { get; set; }
        public string b_sogiayto { get; set; }
        public string b_diachithuongtru { get; set; }
        public string b_sogiaychungnhan { get; set; }
        public string b_sothua { get; set; }
        public string b_tobando { get; set; }
        public string b_thon { get; set; }
        public string b_xa { get; set; }
        public string b_huyen { get; set; }
        public string b_tinh { get; set; }
        public string b_diachithuadat { get; set; }
        public string b_dientich { get; set; }
        public string b_hinhthucsudung { get; set; }
        public string b_mucdichsudung { get; set; }
        public string b_nguongoc { get; set; }
        public string b_ghichu { get; set; }
        public Nullable<System.DateTime> b_ngaycap { get; set; }
        public string b_noicap { get; set; }
        public string b_sovaoso { get; set; }
        public string b_loaidat1 { get; set; }
        public string b_dientich1 { get; set; }
        public string b_loaidat2 { get; set; }
        public string b_dientich2 { get; set; }
        public string b_loainguongoc { get; set; }
        public string b_chuyenquyen { get; set; }
        public string c_xaphuong { get; set; }
        public string c_xa { get; set; }
        public string c_baocao_veviec { get; set; }
        public string c_dondenghi_noidung { get; set; }
        public string d_sogiayto { get; set; }
        public string d_hoten { get; set; }
        public Nullable<System.DateTime> d_ngaysinh { get; set; }
        public string d_gioitinh { get; set; }
        public string d_quoctich { get; set; }
        public string d_nguyenquan { get; set; }
        public string d_hktt { get; set; }
        public string d_loaigiayto { get; set; }
        public Nullable<System.DateTime> d_ngaycap_gt { get; set; }
        public string d_noicap_gt { get; set; }
        public string d_masothue { get; set; }
        public string d_sogiayto1 { get; set; }
        public string d_loaigiayto1 { get; set; }
        public string d_hoten1 { get; set; }
        public Nullable<System.DateTime> d_ngaysinh1 { get; set; }
        public string d_gioitinh1 { get; set; }
        public string d_hktt1 { get; set; }
        public Nullable<System.DateTime> d_ngaycap_gt1 { get; set; }
        public string d_noicap_gt1 { get; set; }
        public string d_loaibiendong { get; set; }
        public string d_noidungbiendong { get; set; }
        public string d_lydobiendong { get; set; }
        public string d_sohopdong { get; set; }
        public string d_noicongchung { get; set; }
        public Nullable<System.DateTime> d_ngaycongchung { get; set; }
        public Nullable<int> d_tienhopdong { get; set; }
        public string d_vitrithuadat { get; set; }
        public string d_thon { get; set; }
        public string d_xa { get; set; }
        public string d_huyen { get; set; }
        public string d_tinh { get; set; }
        public string e_sogiayto { get; set; }
        public string e_hoten { get; set; }
        public Nullable<System.DateTime> e_ngaysinh { get; set; }
        public string e_gioitinh { get; set; }
        public string e_quoctich { get; set; }
        public string e_nguyenquan { get; set; }
        public string e_hktt { get; set; }
        public Nullable<System.DateTime> e_ngaycap_gt { get; set; }
        public string e_noicap_gt { get; set; }
        public string e_masothue { get; set; }
        public string e_giayuyquyenso { get; set; }
        public Nullable<System.DateTime> e_ngayuyquyen { get; set; }
        public Nullable<int> e_doituong { get; set; }
    }
}
