//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public long id { get; set; }
        public string name { get; set; }
        public long job_id { get; set; }
        public int account_id_created { get; set; }
        public int account_id { get; set; }
        public System.DateTime time { get; set; }
        public System.DateTime time_exp { get; set; }
        public Nullable<int> progress_type { get; set; }
        public Nullable<int> label { get; set; }
        public string note { get; set; }
        public int status { get; set; }
    }
}
