//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCaNhan
    {
        public int id { get; set; }
        public Nullable<int> sohokhau_id { get; set; }
        public int infomation_id { get; set; }
        public Nullable<int> fk_id { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<System.DateTime> ngaychet { get; set; }
        public string giaytochet { get; set; }
        public string loaigiayto { get; set; }
        public string sogiayto { get; set; }
        public string gioitinh { get; set; }
        public string quoctich { get; set; }
        public string hktt { get; set; }
        public Nullable<System.DateTime> ngaycap_gt { get; set; }
        public string noicap_gt { get; set; }
        public string masothue { get; set; }
        public Nullable<int> quanhe { get; set; }
        public Nullable<int> hangthuake { get; set; }
        public string ghichuquanhe { get; set; }
        public Nullable<int> marker { get; set; }
        public string note { get; set; }
        public Nullable<int> type { get; set; }
        public string hoten1 { get; set; }
        public Nullable<System.DateTime> ngaysinh1 { get; set; }
        public Nullable<System.DateTime> ngaychet1 { get; set; }
        public string giaytochet1 { get; set; }
        public string loaigiayto1 { get; set; }
        public string sogiayto1 { get; set; }
        public string gioitinh1 { get; set; }
        public string quoctich1 { get; set; }
        public string hktt1 { get; set; }
        public Nullable<System.DateTime> ngaycap_gt1 { get; set; }
        public string noicap_gt1 { get; set; }
        public string masothue1 { get; set; }
        public Nullable<int> quanhe1 { get; set; }
        public string ghichuquanhe1 { get; set; }
        public Nullable<int> songtrendat { get; set; }
    }
}
