//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuaDat
    {
        public int id { get; set; }
        public int infomation_id { get; set; }
        public int type { get; set; }
        public string sogiaychungnhan { get; set; }
        public string sothua { get; set; }
        public string tobando { get; set; }
        public string diachithuadat { get; set; }
        public string dientich { get; set; }
        public string hinhthucsudung { get; set; }
        public string mucdichsudung { get; set; }
        public string nguongoc { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaycap { get; set; }
        public string noicap { get; set; }
        public string sovaoso { get; set; }
        public string loaidat1 { get; set; }
        public string dientich1 { get; set; }
        public string loaidat2 { get; set; }
        public string dientich2 { get; set; }
        public Nullable<int> csh1 { get; set; }
        public Nullable<int> csh2 { get; set; }
    }
}
