//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreoPhuon
    {
        public int id { get; set; }
        public string Images { get; set; }
        public int DvhcC1_id { get; set; }
        public string GoogleMap { get; set; }
        public System.DateTime NgayTreo { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public string note { get; set; }
    }
}
