//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VariationInfo()
        {
            this.HoSoes = new HashSet<HoSo>();
        }
    
        public int Id { get; set; }
        public string VariationType { get; set; }
        public string ContractNumber { get; set; }
        public string NotaryOffice { get; set; }
        public Nullable<System.DateTime> NotaryDate { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public string TaxReductionReason { get; set; }
        public string LandPosition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSo> HoSoes { get; set; }
    }
}
