//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCanBoDiaPhuongC2
    {
        public string AddressName { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string chucvu { get; set; }
        public string gmap { get; set; }
        public string phoneno { get; set; }
        public int thuoccap { get; set; }
        public string note { get; set; }
        public int fk_id { get; set; }
    }
}
