//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vContractHardFile
    {
        public string HardFileLink { get; set; }
        public string address_name { get; set; }
        public string customer_name { get; set; }
        public string service_name { get; set; }
        public string partner_name { get; set; }
        public System.DateTime time { get; set; }
        public int address_id { get; set; }
        public int customer_id { get; set; }
        public int service_id { get; set; }
        public int partner { get; set; }
        public int id { get; set; }
        public int status { get; set; }
    }
}
