//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDi1Cua
    {
        public int id { get; set; }
        public int hoso_id { get; set; }
        public System.DateTime ngaynop { get; set; }
        public System.DateTime ngaytra { get; set; }
        public int canbo1cua { get; set; }
        public string maphieuhen { get; set; }
        public int trangthai { get; set; }
        public int contract_id { get; set; }
        public string name { get; set; }
        public System.DateTime time_created { get; set; }
        public int account_id { get; set; }
        public int service_id { get; set; }
        public int priority { get; set; }
        public int status { get; set; }
        public int address_id { get; set; }
        public int partner { get; set; }
        public int time_exp { get; set; }
        public System.DateTime time { get; set; }
        public string ghichu { get; set; }
        public int account_id_soanthao { get; set; }
        public int step_id { get; set; }
        public string note { get; set; }
        public Nullable<int> noinhan_id { get; set; }
    }
}
