//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHomeWFInOut
    {
        public System.DateTime time { get; set; }
        public string wfNote { get; set; }
        public string fullname { get; set; }
        public string IONote { get; set; }
        public string name { get; set; }
        public long amount { get; set; }
        public int type { get; set; }
    }
}
