//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHoSo
    {
        public System.DateTime time { get; set; }
        public int address_id { get; set; }
        public string address_name { get; set; }
        public string service_name { get; set; }
        public int partner { get; set; }
        public string partner_name { get; set; }
        public string account_name { get; set; }
        public int id { get; set; }
        public int contract_id { get; set; }
        public string name { get; set; }
        public int account_id_soanthao { get; set; }
        public int priority { get; set; }
        public int trang4 { get; set; }
        public int status { get; set; }
        public string sodienthoai { get; set; }
        public int service_id { get; set; }
        public int account_id { get; set; }
        public int step_id { get; set; }
        public int time_exp { get; set; }
        public string sodienthoai_mota { get; set; }
        public int deadline { get; set; }
        public Nullable<int> ngoaigiao { get; set; }
        public Nullable<System.DateTime> time_complete { get; set; }
        public System.DateTime time_created { get; set; }
        public Nullable<int> light { get; set; }
    }
}
