//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMyReward
    {
        public int step_id { get; set; }
        public int type { get; set; }
        public System.DateTime ngaynop { get; set; }
        public int address_id { get; set; }
        public int partner { get; set; }
        public int account_id { get; set; }
        public string address_name { get; set; }
        public string maphieuhen { get; set; }
        public string partner_name { get; set; }
        public string fullname { get; set; }
        public long amount { get; set; }
        public int contract_id { get; set; }
        public string customer_name { get; set; }
        public string note { get; set; }
        public int hoso_id { get; set; }
        public int service_id { get; set; }
        public string service_name { get; set; }
        public int id { get; set; }
        public System.DateTime time { get; set; }
        public int status { get; set; }
        public int dove { get; set; }
        public int remunerate { get; set; }
    }
}
