//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPhongDoVe
    {
        public string name { get; set; }
        public int account_id { get; set; }
        public int service_id { get; set; }
        public string link_filecad { get; set; }
        public string link_gmap { get; set; }
        public string link_filecad_qr { get; set; }
        public string link_gmap_qr { get; set; }
        public string link_flycam { get; set; }
        public string a_hoten { get; set; }
        public string a_gioitinh { get; set; }
        public string a_hktt { get; set; }
        public string a_hoten1 { get; set; }
        public string a_gioitinh1 { get; set; }
        public string a_hktt1 { get; set; }
        public string b_sogiaychungnhan { get; set; }
        public string b_sothua { get; set; }
        public string b_tobando { get; set; }
        public string b_diachithuadat { get; set; }
        public string b_dientichtrenbia { get; set; }
        public string b_hinhthucsudung { get; set; }
        public string b_mucdichsudung { get; set; }
        public Nullable<System.DateTime> b_ngaycap { get; set; }
        public string b_noicap { get; set; }
        public string b_sovaoso { get; set; }
        public string b_loaidat1 { get; set; }
        public string b_dientich1 { get; set; }
        public string b_loaidat2 { get; set; }
        public string b_dientich2 { get; set; }
        public int contract_id { get; set; }
        public int address_id { get; set; }
        public string sodienthoai { get; set; }
        public string sodienthoai_mota { get; set; }
        public int partner { get; set; }
        public string b_dientich { get; set; }
        public int id { get; set; }
        public int hoso_id { get; set; }
        public int status { get; set; }
        public System.DateTime time { get; set; }
        public string scan_bia { get; set; }
        public Nullable<System.DateTime> time_start { get; set; }
        public Nullable<System.DateTime> time_tradiem { get; set; }
        public Nullable<System.DateTime> time_vexong { get; set; }
        public Nullable<System.DateTime> time_dongdau { get; set; }
        public Nullable<System.DateTime> time_thamdinh { get; set; }
        public int dove_account { get; set; }
    }
}
