//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSoanThao
    {
        public int id { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<System.DateTime> exp { get; set; }
        public int status { get; set; }
        public Nullable<int> workflow { get; set; }
        public int Priority { get; set; }
        public string sodienthoai { get; set; }
        public string address_name { get; set; }
        public string service_name { get; set; }
        public string step_name { get; set; }
        public string account_name { get; set; }
        public string partner_name { get; set; }
        public string customer_name { get; set; }
        public int customer_id { get; set; }
        public int address_id { get; set; }
        public int step { get; set; }
        public Nullable<int> account_id { get; set; }
        public int partner { get; set; }
        public string step_code { get; set; }
        public string step_color { get; set; }
        public string partner_code { get; set; }
        public string link_giapha { get; set; }
        public string message { get; set; }
        public int type { get; set; }
        public int service_id { get; set; }
        public Nullable<int> soanthao { get; set; }
    }
}
