//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTheoDoiChi
    {
        public int status { get; set; }
        public string note { get; set; }
        public int id { get; set; }
        public long inout_id { get; set; }
        public long amount { get; set; }
        public string contract_name { get; set; }
        public string category_name { get; set; }
        public string service_name { get; set; }
        public string address_name { get; set; }
        public int category_id { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> contract_id { get; set; }
        public int account_id { get; set; }
        public string fullname { get; set; }
    }
}
