//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTheoDoiTienDo
    {
        public System.DateTime time { get; set; }
        public int partner { get; set; }
        public int address_id { get; set; }
        public string name { get; set; }
        public int contract_id { get; set; }
        public int id { get; set; }
        public int time_exp { get; set; }
        public int account_id { get; set; }
        public string disname { get; set; }
        public int service_id { get; set; }
        public int step_id { get; set; }
        public int status { get; set; }
    }
}
