//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vViecPhaiLam
    {
        public string title { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime time { get; set; }
        public System.DateTime time_progress { get; set; }
        public string result { get; set; }
        public int hoso_id { get; set; }
        public string hoso_name { get; set; }
        public int service_id { get; set; }
        public string service_name { get; set; }
        public int progress_type { get; set; }
        public string fullname { get; set; }
        public int status { get; set; }
        public int account_id { get; set; }
    }
}
