//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wf_hoso_step
    {
        public long id { get; set; }
        public long hoso_id { get; set; }
        public System.DateTime time { get; set; }
        public string note { get; set; }
        public int account_id { get; set; }
        public int step_id { get; set; }
        public Nullable<int> next_step { get; set; }
    }
}
